const produtos = [
  {
    "nome": "Caneca Personalizada de Porcelana 325ml",
    "descricao": "Caneca sublimada com decoração natalina em alta resolução — perfeita para lembranças e presentes.",
    "categoria": "Sublimação",
    "preco": 0,
    "imagem": "caneca.jpg",
    "campanhas": [],
    "estoque": 13,
    "googleDriveLink": "https://drive.google.com/drive/folders/1eoeLBRrRvjSI8Eh_x2fls5GuObwcOuye?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse na Caneca Personalizada 325ml."
  },
  {
    "nome": "Camiseta Branca Personalizada",
    "descricao": "Camiseta 100% poliéster com impressão personalizada — ideal para eventos, brindes e uniformes.",
    "categoria": "Sublimação",
    "preco": 0,
    "imagem": "camiseta.jpg",
    "campanhas": [],
    "estoque": 0,
    "googleDriveLink": "https://drive.google.com/drive/folders/1H_SeK2F5AagvDlhjj1QmpfxSvzuoGAS7?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse em Camisetas Personalizadas."
  },
  {
    "nome": "Camiseta Personalizada",
    "descricao": "Camiseta cinza 100% poliéster com impressão de alta qualidade. Ideal para eventos, brindes e uso pessoal — conforto e estilo em uma só peça.",
    "categoria": "Sublimação",
    "preco": 0,
    "imagem": "camiseta2.jpg",
    "campanhas": [],
    "estoque": 0,
    "googleDriveLink": "https://drive.google.com/drive/folders/1jLYDMKwGv3kQlm35V-vDfzAw4TQ7rPIE?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse na Camiseta Personalizada."
  },
  {
    "nome": "Bolinha de Natal Personalizada",
    "descricao": "Bolinha de acrílico personalizável pronta para enfeitar sua árvore — um toque especial para as festas.",
    "categoria": "Personalizados",
    "preco": 0,
    "imagem": "bolinha-natal.jpg",
    "campanhas": [],
    "estoque": 0,
    "googleDriveLink": "https://drive.google.com/drive/folders/1d-efuSuP3aDRHBACY222oa-o7Lx43JfX?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse em Bolinhas de Natal Personalizadas."
  },
  {
    "nome": "Bolinha de Natal com Foto",
    "descricao": "Bolinha de Natal personalizável pronta para enfeitar sua árvore — um toque especial para as festas.",
    "categoria": "Personalizados",
    "preco": 0,
    "imagem": "bolinha-natal3.jpg",
    "campanhas": [],
    "estoque": 1,
    "googleDriveLink": "https://drive.google.com/drive/folders/1d-efuSuP3aDRHBACY222oa-o7Lx43JfX?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse em Bolinhas de Natal Personalizadas."
  },
  {
    "nome": "Convite Digital",
    "descricao": "Convite digital personalizável pronto para envio via WhatsApp e redes — rápido, prático e econômico.",
    "categoria": "Convites Digitais",
    "preco": 0,
    "imagem": "convite.jpg",
    "campanhas": [],
    "estoque": 1,
    "googleDriveLink": "https://drive.google.com/drive/folders/13I_hq8zmX25LPs_RC3BeEir8MUSUP7eq?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse em Convites Digitais."
  },
  {
    "nome": "Calendário Triangular de Mesa",
    "descricao": "Calendário triangular de mesa personalizado em papel fotográfico com acabamento brilhante. Versão 12 meses ou 6 meses promocional.",
    "categoria": "Personalizados",
    "preco": 0,
    "imagem": "calendario.jpg",
    "campanhas": [],
    "estoque": 100,
    "googleDriveLink": "https://drive.google.com/drive/folders/1VcRuw6APpBgakrEN0IZu9XfJ7krjMamE?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse no Calendário Triangular de Mesa."
  },
  {
    "nome": "Plaquinha Acrílica 15×10 (Acrílico)",
    "descricao": "Plaquinha acrílica 15×10 cm com impressão em alta qualidade. Acabamento polido e cantos arredondados — ideal para brindes e sinalização elegante.",
    "categoria": "Personalizados",
    "preco": 0,
    "imagem": "Placa-de-Acrílico.jpg",
    "campanhas": [],
    "estoque": 3,
    "googleDriveLink": "https://drive.google.com/drive/folders/1kLbWnTpiKRTnKgC4h11Oqb3hv2w6MS60?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse na Plaquinha Acrílica 15x10."
  },
  {
    "nome": "Manutenção de Computador e Notebook",
    "descricao": "Limpeza, formatação, reparos, upgrade e recuperação de dados — suporte técnico especializado.",
    "categoria": "Manutenção",
    "preco": 0,
    "imagem": "manutencaopc.png",
    "campanhas": [],
    "estoque": 1,
    "googleDriveLink": "https://site-servico-manutencao.netlify.app/",
    "phone": "5532991992905",
    "message": "Olá! Preciso de assistência em manutenção de computador/notebook."
  },
  {
    "nome": "Azulejo Decorativo Personalizado",
    "descricao": "Azulejo cerâmico 20×20 cm com impressão direta e esmaltação protetora. Ideal para lembranças, decoração de ambientes e presentes — acabamento resistente e fácil de limpar.",
    "categoria": "Sublimação",
    "preco": 0,
    "imagem": "azulejo.jpg",
    "campanhas": [],
    "estoque": 3,
    "googleDriveLink": "https://drive.google.com/drive/folders/1woHp58fyr0saEi-0Bcq2HGM_yruRbku_?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse no Azulejo 15x15."
  },
  {
    "nome": "Caneca Jateada Personalizada",
    "descricao": "Caneca jateada em vidro/cerâmica com acabamento acetinado (frosted). Impressão personalizada em alta definição — toque sofisticado e ideal para presentes corporativos e lembranças especiais.",
    "categoria": "Sublimação",
    "preco": 0,
    "imagem": "caneca-jateada.jpg",
    "campanhas": [],
    "estoque": 1,
    "googleDriveLink": "https://drive.google.com/drive/folders/1Ht3eppk8bnNr3u9Ze7rBGUoBhIAXNCei?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse na Caneca Jateada personalizada."
  },
  {
    "nome": "Nécessaire Personalizada",
    "descricao": "Nécessaire personalizada com diversos tamanhos e materiais. Ideal para organização pessoal, brindes corporativos e presentes exclusivos.",
    "categoria": "Sublimação",
    "preco": 0,
    "imagem": "necessaire.jpg",
    "campanhas": [],
    "estoque": 10,
    "googleDriveLink": "https://drive.google.com/drive/folders/1ZFc-dSCURNePIjR0fcpA8-AvooOYkc4P?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse na Nécessaire personalizada."
  },
  {
    "nome": "Plaquinha Acrílica 15×10 (Acrílico)",
    "descricao": "Plaquinha acrílica 15×10 cm com impressão em alta qualidade. Acabamento polido e cantos arredondados — ideal para brindes e sinalização elegante.",
    "categoria": "Personalizados",
    "preco": 30,
    "imagem": "natal-verde.jpg",
    "campanhas": [],
    "estoque": 3,
    "googleDriveLink": "https://drive.google.com/drive/folders/1kLbWnTpiKRTnKgC4h11Oqb3hv2w6MS60?usp=sharing",
    "phone": "5532991657472",
    "message": "Olá! Tenho interesse na Plaquinha Acrílica 15x10."
  }
]